# Generated by Django 3.1.2 on 2020-11-03 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onboarded',
            old_name='name',
            new_name='test',
        ),
    ]
