# Generated by Django 3.1.2 on 2020-11-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_1', '0002_auto_20201103_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarded',
            name='test',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
