# Generated by Django 3.1.2 on 2020-11-03 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_1', '0002_remove_registration_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_first_1.freedemo')),
            ],
        ),
        migrations.AlterField(
            model_name='onboarded',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_first_1.registrations'),
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
