# Generated by Django 3.1.2 on 2020-11-03 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_1', '0003_auto_20201103_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freedemo',
            old_name='occupation',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='registrations',
            old_name='course',
            new_name='job',
        ),
        migrations.AlterField(
            model_name='freedemo',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='onboarded',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_first_1.registrations'),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_first_1.freedemo'),
        ),
    ]
