# Generated by Django 3.1.2 on 2020-11-03 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_1', '0003_auto_20201103_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onboarded',
            old_name='test',
            new_name='name',
        ),
    ]
