# Generated by Django 3.1.2 on 2020-11-03 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_1', '0004_auto_20201103_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freedemo',
            old_name='profile',
            new_name='ssn',
        ),
    ]
