# Generated by Django 3.1.3 on 2020-11-12 00:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='djangouser',
            new_name='Django_user',
        ),
    ]
